// Mocks generated by Mockito 5.4.5 from annotations
// in send_money/test/mocks/home_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money/dto/transaction.dart' as _i5;
import 'package:send_money/home/interactor/home_interactor.dart' as _i2;
import 'package:send_money/service/transaction_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeInteractor].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeInteractor extends _i1.Mock implements _i2.HomeInteractor {
  MockHomeInteractor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> getWallet() => (super.noSuchMethod(
        Invocation.method(
          #getWallet,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);
}

/// A class which mocks [TransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionService extends _i1.Mock
    implements _i4.TransactionService {
  MockTransactionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.Transaction>> getTransactions() => (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i5.Transaction>>.value(<_i5.Transaction>[]),
      ) as _i3.Future<List<_i5.Transaction>>);
}
